### ISSUE TITLE
CRMesh version 0.8.0 breaks this service

### ISSUE THREAD

**Issue by adamrmcclain** [danisla/iot-homebrite-led-bulb#1]
Hello,

I've recently been playing around with this, and just wanted to let you know if you don't add a version of 0.7.0 in your requirements.txt this will no longer work. They changed a lot of things around in the crmesh library.

**Comment by danisla** [comment]
Thanks for the heads up! I just updated the requirements.txt to fix the version until I get around to making it work with the newer version.
